#%RAML 1.0 DataType
displayName: ELK Loader Strategy
description: Models a ELK Loader Strategy
properties:
  collectors:
    description: | 
              Comma separated set of collectors that should be executed. Possible values are:
            
              Available for all deployment models:
                - ap: Automated Policies              
                - apc: API Clients
                - apm: API Manager
                - arm: Runtime Manager   
                - core: Core Services
                - dc: Design Center
                - ex: Exchange
                
              Not available for PCE deployment model:
                - amq: Anypoint MQ
                - apma: API Manager Analytics                                          
                - ch: Cloudhub   
                - rtf: Runtime Fabric 
    type: array
    items: string
    default: ["all"]    
    required: false    
  loaderDetails:
    type: object
    properties:
      strategy:
        type: string
      rawData:
        type: string
      elk:
        type: object
        properties: 
          host:
            type: string
          port:
            type: string
          user:
            type: string
          password: 
            type: string 
          platformMetricsIndex: 
            type: string 
          platformBenefitsIndex: 
            type: string 
example: !include ../../examples/loaders/elk.json            