#%RAML 1.0 DataType
displayName: Tableau Loader Strategy
description: Models a Tableau Loader Strategy
properties:
  collectors: 
    description: | 
              Comma separated set of collectors that should be executed. Possible values are:
            
              Available for all deployment models:
                - ap: Automated Policies              
                - apc: API Clients
                - apm: API Manager
                - arm: Runtime Manager   
                - core: Core Services
                - dc: Design Center
                - ex: Exchange
                
              Not available for PCE deployment model:
                - amq: Anypoint MQ
                - apma: API Manager Analytics                                          
                - ch: Cloudhub   
                - rtf: Runtime Fabric 
    type: array
    items: string
    default: ["all"]    
    required: false
  loaderDetails:
    type: object
    properties:
      strategy:
        type: string
      rawData:
        type: string
      outputDir:
        type: string
example: !include ../../examples/loaders/tableau.json