#%RAML 1.0 DataType
displayName: SDLC Metrics Loader Response Datatype
description: Models the response aftter posting SDLC metrics
properties:
  message:
    type: string
    default: "Not implemented"