#%RAML 1.0 Trait
queryParameters:
  collectors:
    description: | 
                Comma separated set of collectors that should be executed. Possible values are:
              
                Available for all deployment models:
                  - ap: Automated Policies              
                  - apc: API Clients
                  - apm: API Manager
                  - arm: Runtime Manager   
                  - core: Core Services
                  - dc: Design Center
                  - ex: Exchange
                  
                Not available for PCE deployment model:
                  - amq: Anypoint MQ
                  - apma: API Manager Analytics                                          
                  - ch: Cloudhub   
                  - rtf: Runtime Fabric 
    default: all    
    required: false
    type: string
    pattern: ^all|([ap|apc|apm|arm|core|dc|ex|amq|apma|ch|rtf]+([,[ap|apc|apm|arm|core|dc|ex|amq|apma|ch|rtf]])*)$  