#%RAML 1.0 DataType
displayName: Anypoint Design Center Datatype
description: This datatype models the metrics obtained from Design Center
properties:
  total:
    type: integer
    displayName: Assets Total
    description: Count of total assets per BG
  apiSpecs:
    type: integer
    displayName: API Specs Total	
    description: Count of total API specs per BG
  fragments:
    type: integer
    displayName: Fragments Total
    description: Count of total RAML fragments per BG
  flowDesignerApps:
    type: integer
    displayName: Flow Designer Apps Total
    description: Count of total Flow Designer applications per BG
