#%RAML 1.0 Library
usage: Anypoint headers for accessing platform APIs. 
traits:
  hasHeaders:
    description: Headers for accessing the Anypoint Platform.  Includes authentication and org information.
    displayName: Anypoint Platform Headers
    headers:
      X-ANYPNT-USERNAME:
        description: |
          Receives the username used to login to Anypoint Platform.
        type: string
        required: false
      X-ANYPNT-PASSWORD:
        description: |
          Receives a plain text or Base64-encoded password used to login to Anypoint Platform.
        type: string
        required: false
      X-ANYPNT-CLIENT-ID:
        description: |
          Receives the connected app client id used to login to Anypoint Platform.
        type: string
        required: false
      X-ANYPNT-CLIENT-SECRET:
        description: |
          Receives the connected app client secret to login to Anypoint Platform.
        type: string
        required: false
      X-ANYPNT-ORG-ID:
        description: Anypoint root Organization ID for acquiring metrics.
        type: string
        required: true
