#%RAML 1.0 DataType
displayName: AMQ Region Datatype
description: Models Anypoint-MQ stats by environment (summary or region)
properties:
  production:
    type: !include environment.raml
    displayName: Production
    description: Provides metrics aggregated by Production environments
  sandbox:
    type: !include environment.raml
    displayName: Sandbox
    description: Provides metrics aggregated by Sandbox environments
