#%RAML 1.0 SecurityScheme
description: | 
      This API supports Basic Authentication, and can be used only for platform user authentication 
      This mechanism is mandatory if the password contains special characters
      For Connected Apps authentication, connected-app-auth security scheme must be used.
type: Basic Authentication