#%RAML 1.0 SecurityScheme
description: Authentication scheme for plaform users. If password contains special characters, Basic Authentication must be used.
displayName: Platform User Authentication Headers
type: x-platform-auth
describedBy:
  headers:
    X-ANYPNT-USERNAME:
      description: |
        Receives the username used when login to Anypoint Platform.
      type: string
      required: true
    X-ANYPNT-PASSWORD:
      description: |
        Receives a text/plain password used when login to Anypoint Platform.
      type: string
      required: true