#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f724e6da-ec13-4c76-b7c7-eeaf154323e3/api/ # baseUri: https://localhost:8081/api/
title: Metrics Accelerator API
description: Metrics Accelerator API to obtain and generate operational and business metrics
version: v1
protocols: 
  - HTTPS
  
securedBy: [basic-auth, platform-auth, connected-app-auth]
securitySchemes:
  basic-auth:
    description: | 
      This API supports Basic Authentication, and can be used only for platform user authentication 
      This mechanism is mandatory if the password contains special characters
      For Connected Apps authentication, connected-app-auth security scheme must be used.
    type: Basic Authentication
  platform-auth:
    description: Authentication scheme for plaform users. If password contains special characters, Basic Authentication must be used.
    displayName: Platform User Authentication Headers
    type: x-platform-auth
    describedBy:
      headers:
        X-ANYPNT-USERNAME:
          description: |
            Receives the username used when login to Anypoint Platform.
          type: string
          required: true
        X-ANYPNT-PASSWORD:
          description: |
            Receives a text/plain password used when login to Anypoint Platform.
          type: string
          required: true
  connected-app-auth:
    description: Authentication scheme for connected apps.
    displayName: Connected App Authentication Headers
    type: x-connected-app-auth
    describedBy:
      headers:
        X-ANYPNT-CLIENT-ID:
          description: |
            Receives the connected app client id used when login to Anypoint Platform.
          type: string
          required: true
        X-ANYPNT-CLIENT-SECRET:
          description: |
            Receives the connected app client secret when login to Anypoint Platform.
          type: string
          required: true
/platform-metrics:
  get:
    headers:
      X-ANYPNT-ORG-ID: string
    queryParameters:
      collectors:
        description: | 
            Comma separated set of collectors that should be executed. Possible values are:
            
            Available for all deployment models:
              - ap: Automated Policies              
              - apc: API Clients
              - apm: API Manager
              - arm: Runtime Manager   
              - core: Core Services
              - dc: Design Center
              - ex: Exchange
              
            Not available for PCE deployment model:
              - amq: Anypoint MQ
              - apma: API Manager Analytics                                          
              - ch: Cloudhub   
              - rtf: Runtime Fabric
              
        default: all
           
        required: false
        type: string
        pattern: ^all|([ap|apc|apm|arm|core|dc|ex|amq|apma|ch|rtf]+([,[ap|apc|apm|arm|core|dc|ex|amq|apma|ch|rtf]])*)$  
      raw:
        description: "Provide raw data"
        type: boolean
        default: false
    responses:
      200:
        body:
          application/json:
  /load:
    post:
      headers:
        X-ANYPNT-ORG-ID: string 
      body:
        application/json:
          
      responses:
        201:
          body:
            application/json:
              
    
/business-metrics:
  get:
    headers:
      X-ANYPNT-ORG-ID: string
    queryParameters:
      developAPIHistoricTime:
        description: "Historic average time to develop an API (days)"
        type: number
      developAPICurrentTime:
        description: "Current average time to develop an API (days)"
        type: number
      maintainAPIHistoricTime:
        description: "Historic average time to maintain an API (days)"
        type: number
      maintainAPICurrentTime:
        description: "Current average time to maintain an API (days)"
        type: number
      developerDayRate:
        description: "Average Developer's day rate "
        type: number
    responses:
      200:
        body:
          application/json:
  /load:
    post:
      headers:
        X-ANYPNT-ORG-ID: string
      body:
        application/json:
      responses:
        201:
          body:
            application/json:  
/sdlc-metrics:
  get:
    queryParameters:
      raw:
        description: "Provide raw data"
        type: boolean
        default: false
    responses:
      200:
        body:
          application/json:
  /load:
    post:
      body:
        application/json:
          
      responses:
        201:
          body:
            application/json:


            