#%RAML 1.0
title: Metrics Accelerator API
description: Metrics Accelerator API to obtain and generate operational and business metrics
version: v1
protocols: 
  - HTTPS
  
uses:
  anypoint: libraries/anypoint-library.raml

/platform-metrics:
  is: [anypoint.hasHeaders]
  get:
    queryParameters:
      collectors:
        description: | 
            Comma separated set of collectors that should be executed. Possible values are:
            
            Available for all deployment models:
              - ap: Automated Policies              
              - apc: API Clients
              - apm: API Manager
              - arm: Runtime Manager   
              - core: Core Services
              - dc: Design Center
              - ex: Exchange
              - amq: Anypoint MQ
              - osv2: ObjectStore V2
              
            Not available for PCE deployment model:
              - amq: Anypoint MQ
              - apma: API Manager Analytics                                          
              - ch: Cloudhub   
              - rtf: Runtime Fabric
              
        default: all
           
        required: false
        type: string
        pattern: ^all|([ap|apc|apm|arm|core|dc|ex|amq|apma|ch|rtf|osv2]+([,[ap|apc|apm|arm|core|dc|ex|amq|apma|ch|rtf|osv2]])*)$  
      raw:
        description: "Provide raw data"
        type: boolean
        default: false
    responses:
      200:
        body:
          application/json:
  /load:
    is: [anypoint.hasHeaders]
    post:
      body:
        application/json:
          
      responses:
        201:
          body:
            application/json:
              
    
/business-metrics:
  is: [anypoint.hasHeaders]
  get:
    queryParameters:
      developAPIHistoricTime:
        description: "Historic average time to develop an API (days)"
        type: number
      developAPICurrentTime:
        description: "Current average time to develop an API (days)"
        type: number
      maintainAPIHistoricTime:
        description: "Historic average time to maintain an API (days)"
        type: number
      maintainAPICurrentTime:
        description: "Current average time to maintain an API (days)"
        type: number
      developerDayRate:
        description: "Average Developer's day rate "
        type: number
    responses:
      200:
        body:
          application/json:
  /load:
    is: [anypoint.hasHeaders]
    post:
      body:
        application/json:
      responses:
        201:
          body:
            application/json:  
/sdlc-metrics:
  get:
    queryParameters:
      raw:
        description: "Provide raw data"
        type: boolean
        default: false
    responses:
      200:
        body:
          application/json:
  /load:
    post:
      body:
        application/json:
          
      responses:
        201:
          body:
            application/json:


            