#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f724e6da-ec13-4c76-b7c7-eeaf154323e3/api/ # baseUri: https://localhost:8081/api/
title: Metrics Framework API
description: Metrics Framework API to obtain and generate operational and business metrics
version: v1
protocols: 
  - HTTPS
  
securedBy: [basic-auth, headers-auth]
securitySchemes:
  basic-auth:
    description: This API supports Basic Authentication. This mechanism is mandatory if the password contains special characters.
    type: Basic Authentication
  headers-auth:
    description: This API supports Authentication based on custom headers.
    displayName: Headers Authentication
    type: x-custom
    describedBy:
      headers:
        X-ANYPNT-USERNAME:
          description: |
            Receives the username used when login to Anypoint Platform.
          type: string
        X-ANYPNT-PASSWORD:
          description: |
            Receives a text/plain password used when login to Anypoint Platform. 
          type: string
       
/platform-metrics:
  get:
    headers:
      X-ANYPNT-ORG-ID: string
    queryParameters:
      raw:
        description: "Provide raw data"
        type: boolean
        default: false
    responses:
      200:
        body:
          application/json:
  /load:
    post:
      headers:
        X-ANYPNT-ORG-ID: string 
      body:
        application/json:
          
      responses:
        201:
          body:
            application/json:
              
    
/business-metrics:
  get:
    headers:
      X-ANYPNT-ORG-ID: string
    queryParameters:
      developAPIHistoricTime:
        description: "Historic average time to develop an API (days)"
        type: number
      developAPICurrentTime:
        description: "Current average time to develop an API (days)"
        type: number
      maintainAPIHistoricTime:
        description: "Historic average time to maintain an API (days)"
        type: number
      maintainAPICurrentTime:
        description: "Current average time to maintain an API (days)"
        type: number
      developerDayRate:
        description: "Average Developer's day rate "
        type: number
    responses:
      200:
        body:
          application/json:
  /load:
    post:
      headers:
        X-ANYPNT-ORG-ID: string
      body:
        application/json:
      responses:
        201:
          body:
            application/json:  
/sdlc-metrics:
  get:
    queryParameters:
      raw:
        description: "Provide raw data"
        type: boolean
        default: false
    responses:
      200:
        body:
          application/json:
  /load:
    post:
      body:
        application/json:
          
      responses:
        201:
          body:
            application/json:


            