name: Run Munit Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
      - main
  push:
    branches:
      - pipeline

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: adopt
          architecture: x64
          cache: maven
      - name: Generate settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: |
            [
              {
                "id": "mulesoft-ee",
                "name": "MuleSoft EE",
                "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: |
            [
              {
                "id": "mulesoft-ee",
                "username": MAVEN_USERNAME,
                "password": MAVEN_PASSWORD
              }
            ]
      - name: Run MUnit
        run: mvn -B clean test
        env:
          MAVEN_USERNAME: ${{ secrets.EE_USER }}
          MAVEN_PASSWORD: ${{ secrets.EE_PASS }}
